[build]
  command = "rm ./go.mod && npm install --production && hugo --gc -v --minify --cleanDestinationDir  -s ./exampleSite --themesDir ../.. --enableGitInfo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.104.3"
