[build]
  command = "cd themes/hugo-theme-luna && npm install postcss-cli -g && npm install --production && cd ../../ && hugo --gc --minify --cleanDestinationDir --enableGitInfo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"
  NODE_VERSION = "22.19.0"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"
        [plugins.inputs]
            debug = true
    package = "@netlify/plugin-lighthouse"
