[build]
  command = "cd themes/hugo-theme-luna && npm install postcss-cli -g && npm install --production && cd ../../ && hugo --gc -v --minify --cleanDestinationDir --enableGitInfo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.104.3"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"
        [plugins.inputs]
            debug = true